---
- name: smartd | Deploy smartd.conf
  ansible.builtin.template:
    src: "smartd.j2"
    dest: "{{ hostvars[inventory_hostname]['smartd_conf_dest'] +
      '/smartd.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "smartd -q onecheck -c %s"
  notify:
    - "Restart smartd"
- name: smartd | Enable smartd service
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['smartd_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['smartd'] is defined"
    - "hostvars[inventory_hostname]['smartd'] != ''"
    - "hostvars[inventory_hostname]['smartd'] |
       community.general.json_query(vars['smartd_enable']) is defined"
    - "hostvars[inventory_hostname]['smartd'] |
       community.general.json_query(vars['smartd_enable']) == 'true'"
  vars:
    smartd_enable: "[] | map(&enable || 'false', @) | [0]"
