---
- include: pre_requisite.yml
- include: packages.yml
  when:
  - "hostvars[inventory_hostname]['smartd_install_package'] is defined"
  - "hostvars[inventory_hostname]['smartd_install_package'] == 'true'"
- include: deploy_smartd.yml
  when:
  - "vars['smartd'] is defined"
- include: deploy_smartd_options.yml
  when:
  - "vars['smartd_options'] is defined"
