---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['smartd'] is defined"
    - "hostvars[inventory_hostname]['smartd'] != ''"
    - "hostvars[inventory_hostname]['smartd'] |
       community.general.json_query(vars['smartd_install_package']) is defined"
    - "hostvars[inventory_hostname]['smartd'] |
       community.general.json_query(vars['smartd_install_package']) == 'true'"
  vars:
    smartd_install_package: "[] | map(&install_package || 'false', @) | [0]"
- ansible.builtin.include_tasks:
    file: "deploy_smartd.yml"
  when:
    - "vars['smartd'] is defined"
- ansible.builtin.include_tasks:
    file: "deploy_smartd_options.yml"
  when:
    - "vars['smartd_options'] is defined"
