---
- name: smartd | Add the OS specific variables
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: smartd | Set facts about configuration
  ansible.builtin.set_fact:
    smartd_devices: "{{ hostvars[inventory_hostname]['smartd'] |
      community.general.json_query('[].devices[]') }}"
    smartd_options: "{{ hostvars[inventory_hostname]['smartd'] |
      community.general.json_query('[].options[]') }}"
  when:
    - "hostvars[inventory_hostname]['smartd'] is defined"
    - "hostvars[inventory_hostname]['smartd'] != ''"
- name: smartd | Create smartd attribute log directory
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['smartd_attributelog_path'] }}"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"
    recurse: "no"
  when:
    - "hostvars[inventory_hostname]['smartd_attributelog_path'] is defined"
    - "hostvars[inventory_hostname]['smartd_attributelog_path'] != ''"
    - "hostvars[inventory_hostname]['smartd_create_attrbutelog_path'] is defined"
    - "hostvars[inventory_hostname]['smartd_create_attrbutelog_path'] == 'true'"
