---
- name: Start smartd
  service:
    name: "{{ hostvars[inventory_hostname]['smartd_service'] }}"
    state: "restarted"
    enabled: "yes"
  when:
  - "hostvars[inventory_hostname]['smartd_restart'] is defined"
  - "hostvars[inventory_hostname]['smartd_restart'] == 'true'"
